#!/usr/bin/env bash
#
# Rebuilds src/vendor/keysense-hashes.js, the only generated file in this repo.
#
#   bash tools/build-crypto.sh          write the bundle
#   bash tools/build-crypto.sh --check  rebuild to a temp file and diff
#
# The --check form is what an auditor runs: it proves the committed artifact is
# exactly what the pinned inputs produce, with no trust in whoever built it.
#
# Reproducibility notes:
#   - esbuild output is a pure function of (esbuild version, input bytes, flags).
#     There are no timestamps, no randomness, no machine identifiers, and it is
#     the same Go binary on every architecture.
#   - esbuild writes each input file's path into the output as a comment, and
#     those paths are relative to the working directory. So this must run from
#     the repository root with node_modules directly beneath it. The check below
#     enforces that.
#   - Source maps are deliberately not enabled; they would embed absolute paths.
#   - The output is NOT minified. 33 KB of readable noble source next to a
#     760 KB ethers is worth far more to a reviewer than the space it saves.

set -euo pipefail

NOBLE_VERSION="1.5.0"
NOBLE_INTEGRITY="sha512-1j6kQFb7QRru7eKN3ZDvRcP13rugwdxZqCjbiAVZfIJwgj2A65UmT4TgARXGlXgnRkORLTDTrO19ZErt7+QXgA=="
ESBUILD_VERSION="0.28.1"
OUT="src/vendor/keysense-hashes.js"

if [ ! -f package.json ] || [ ! -f tools/crypto-entry.mjs ]; then
  echo "error: run this from the repository root" >&2
  exit 1
fi

echo "verifying @noble/hashes@${NOBLE_VERSION} against the pinned npm integrity hash"
ACTUAL_INTEGRITY=$(npm view "@noble/hashes@${NOBLE_VERSION}" dist.integrity)
if [ "$ACTUAL_INTEGRITY" != "$NOBLE_INTEGRITY" ]; then
  echo "error: npm integrity mismatch" >&2
  echo "  expected ${NOBLE_INTEGRITY}" >&2
  echo "  actual   ${ACTUAL_INTEGRITY}" >&2
  exit 1
fi

rm -rf node_modules/@noble
npm install --no-save --no-audit --no-fund --ignore-scripts "@noble/hashes@${NOBLE_VERSION}" >/dev/null

TARGET="$OUT"
TMP=""
if [ "${1:-}" = "--check" ]; then
  TMP=$(mktemp)
  TARGET="$TMP"
fi

npx --yes "esbuild@${ESBUILD_VERSION}" tools/crypto-entry.mjs \
  --bundle \
  --format=iife \
  --global-name=KeySenseHashes \
  --target=es2020 \
  --charset=utf8 \
  --legal-comments=inline \
  --banner:js="/* KeySense vendored hashes: blake2b + sha3_256 from @noble/hashes@${NOBLE_VERSION} (MIT, Paul Miller).
   Generated by tools/build-crypto.sh with esbuild@${ESBUILD_VERSION}. Do not edit by hand.
   Verify this file reproduces from its pinned inputs: bash tools/build-crypto.sh --check */" \
  --outfile="$TARGET" >/dev/null

if [ -n "$TMP" ]; then
  if diff -u "$OUT" "$TMP"; then
    echo "OK: ${OUT} reproduces byte for byte from the pinned inputs"
    rm -f "$TMP"
  else
    echo "MISMATCH: ${OUT} does not match a fresh build" >&2
    rm -f "$TMP"
    exit 1
  fi
else
  echo "wrote ${OUT} ($(wc -c < "$OUT") bytes)"
  echo "sha384-$(openssl dgst -sha384 -binary "$OUT" | openssl base64 -A)"
fi
